server {
  listen 80;
  # Indica que este servidor Nginx escuchará solicitudes HTTP en el puerto 80 dentro del contenedor

  location / {
    # Bloque que maneja todas las rutas que empiezan con "/"
    # (en este caso, todo el sitio web)

    root /usr/share/nginx/html;
    # Directorio raíz desde donde se servirán los archivos estáticos (HTML/CSS/JS)

    index index.html;
    # Archivo por defecto cuando se solicita un directorio (por ejemplo "/")

    try_files $uri $uri/ /index.html;
    # Intenta servir:
    # 1) El archivo exacto solicitado ($uri)
    # 2) Si no existe, intenta como directorio ($uri/)
    # 3) Si no existe ninguno, cae a /index.html
    # Esto es útil para SPAs (Single Page Applications) con rutas del lado del cliente
  }
}
