name: taskmanager

services:
  # =========================
  # PostgreSQL (único)
  # =========================
  postgres_a:
    image: postgres:16-alpine
    container_name: taskmanager-postgres-a
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - pgdata_a:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

  # =========================
  # Mongo A (task_logs)
  # =========================
  mongo_a:
    image: mongo:7
    container_name: taskmanager-mongo-a
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodata_a:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval 'db.runCommand({ ping: 1 }).ok' | grep 1 >/dev/null || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

  # =========================
  # Mongo B (access_logs)
  # =========================
  mongo_b:
    image: mongo:7
    container_name: taskmanager-mongo-b
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27018:27017"
    volumes:
      - mongodata_b:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval 'db.runCommand({ ping: 1 }).ok' | grep 1 >/dev/null || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

  # =========================
  # RabbitMQ
  # =========================
  rabbitmq:
    image: rabbitmq:3-management
    container_name: taskmanager-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

  # =========================
  # Mosquitto MQTT
  # =========================
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: taskmanager-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    healthcheck:
      test: ["CMD-SHELL", "mosquitto_sub -h localhost -t '$$SYS/broker/version' -C 1 -W 2 >/dev/null 2>&1 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

  # =====================================================
  # BACKEND AUTH (8000) - desde Docker Hub
  # =====================================================
  auth_service:
    image: juantulcanaza/taskmanager-backend:latest
    container_name: taskmanager-auth
    command: ["uvicorn", "app.main_auth:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_MIN: ${JWT_EXPIRES_MIN}
      CORS_ORIGINS: ${CORS_ORIGINS}

      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: postgres_a
      POSTGRES_PORT: 5432

      # Settings lo exige
      MONGO_A_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_A_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_A_HOST: mongo_a
      MONGO_A_PORT: 27017
      MONGO_A_DB: ${MONGO_A_DB}

      MONGO_B_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_B_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_B_HOST: mongo_b
      MONGO_B_PORT: 27017
      MONGO_B_DB: ${MONGO_B_DB}

    depends_on:
      postgres_a:
        condition: service_healthy
    restart: unless-stopped

  # =====================================================
  # BACKEND A (8001) - desde Docker Hub
  # =====================================================
  backend_a:
    image: juantulcanaza/taskmanager-backend:latest
    container_name: taskmanager-backend-a
    command: ["uvicorn", "app.main_a:app", "--host", "0.0.0.0", "--port", "8001"]
    ports:
      - "8001:8001"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: postgres_a
      POSTGRES_PORT: 5432

      MONGO_A_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_A_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_A_HOST: mongo_a
      MONGO_A_PORT: 27017
      MONGO_A_DB: ${MONGO_A_DB}

      MONGO_B_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_B_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_B_HOST: mongo_b
      MONGO_B_PORT: 27017
      MONGO_B_DB: ${MONGO_B_DB}

      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_MIN: ${JWT_EXPIRES_MIN}
      CORS_ORIGINS: ${CORS_ORIGINS}

      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_URL: "amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672/"

      MQTT_HOST: mosquitto
      MQTT_PORT: 1883
      MQTT_TOPIC: ${MQTT_TOPIC}

      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_TLS: ${SMTP_TLS}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      ADMIN_NOTIFY_TO: ${ADMIN_NOTIFY_TO}
      SMTP_FROM: ${SMTP_FROM}

    depends_on:
      postgres_a:
        condition: service_healthy
      mongo_a:
        condition: service_healthy
      mongo_b:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      mosquitto:
        condition: service_healthy
    restart: unless-stopped

  # =====================================================
  # BACKEND B (8002) - desde Docker Hub
  # =====================================================
  backend_b:
    image: juantulcanaza/taskmanager-backend:latest
    container_name: taskmanager-backend-b
    command: ["uvicorn", "app.main_b:app", "--host", "0.0.0.0", "--port", "8002"]
    ports:
      - "8002:8002"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: postgres_a
      POSTGRES_PORT: 5432

      MONGO_A_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_A_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_A_HOST: mongo_a
      MONGO_A_PORT: 27017
      MONGO_A_DB: ${MONGO_A_DB}

      MONGO_B_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_B_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_B_HOST: mongo_b
      MONGO_B_PORT: 27017
      MONGO_B_DB: ${MONGO_B_DB}

      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_MIN: ${JWT_EXPIRES_MIN}
      CORS_ORIGINS: ${CORS_ORIGINS}

    depends_on:
      postgres_a:
        condition: service_healthy
      mongo_a:
        condition: service_healthy
      mongo_b:
        condition: service_healthy
    restart: unless-stopped

  # =====================================================
  # FRONTEND A (8080) - desde Docker Hub
  # =====================================================
  frontend:
    image: juantulcanaza/taskmanager-frontend:latest
    container_name: taskmanager-frontend-a
    ports:
      - "8080:80"
    depends_on:
      - auth_service
      - backend_a
      - backend_b
    restart: unless-stopped

  # =====================================================
  # FRONTEND B (8081) - desde Docker Hub
  # =====================================================
  frontend_b:
    image: juantulcanaza/taskmanager-frontend-b:latest
    container_name: taskmanager-frontend-b
    ports:
      - "8081:80"
    depends_on:
      - auth_service
      - backend_b
    restart: unless-stopped

volumes:
  pgdata_a:
  mongodata_a:
  mongodata_b:
  mosquitto_data:
  mosquitto_log:
